# Site settings
title: delphyne
email: delphyne+ghpages@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Github hosted site for Maven artifacts, sources, and Javadocs of open source 
  software written by Brian M. Carr
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://github.com/delphyne" # the base hostname & protocol for your site
twitter_username: brianmcarr
github_username:  delphyne
include: [".m2", ".docs"]
# Build settings
markdown: kramdown
